dist: xenial
sudo: required

language: ruby
cache: bundler

addons:
  postgresql: 10

services:
  - xvfb

addons:
  chrome: stable

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - bundle install
  - bundle exec rake db:setup
  - xvfb-run -a bundle exec rspec
