dist: xenial
sudo: required

language: ruby

services:
  - postgresql

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install: gem install bundler -v '< 2.0'

before_script:
  - cp config/database.yml.travis config/database.yml
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bundle install
  - bundle exec rake db:setup
  - bundle exec rspec
