dist: xenial
sudo: true

language: ruby

services:
  - postgresql

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

before_install: gem install bundler -v '< 2.0'

before_script:
  - cp config/database.yml.travis config/database.yml
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - bundle install
  - bundle exec rake db:setup
  - bundle exec rspec
