# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby for more details

version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
        - RACK_ENV=test
        - RAILS_ENV=test
        - DATABASE_URL=postgres://testuser:testpass@127.0.0.1:5432/mahbucket_test

      - image: circleci/postgres:10-alpine-ram
        environment:
          - POSTGRES_USER=testuser
          - POSTGRES_PASSWORD=testpass
          - POSTGRES_DB=mahbucket_test

    working_directory: ~/mahbucket

    steps:
      - checkout
      - ruby/install-deps

      - run:
          name: Install Chromedriver latest version
          command: |
            sudo apt update
            sudo apt install lsb-release libappindicator3-1 libgbm1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome

      - run:
          name: Set up database
          command: |
            bundle exec rake db:create db:schema:load

      - run:
          name: Brakeman
          command: bundle exec brakeman

      - ruby/rubocop-check
      - ruby/rspec-test
