# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
        - RACK_ENV=test
        - RAILS_ENV=test
        - DATABASE_URL=postgres://testuser:testpass@127.0.0.1:5432/mahbucket_test

      - image: circleci/postgres:10-alpine-ram
        environment:
          - POSTGRES_USER=testuser
          - POSTGRES_PASSWORD=testpass
          - POSTGRES_DB=mahbucket_test

    working_directory: ~/mahbucket

    steps:
      - checkout

      - restore_cache:
          keys:
          - bundle-cache-{{ checksum "Gemfile.lock" }}
          - bundle-cache-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Install Chromedriver latest version
          command: |
            sudo apt update
            sudo apt install lsb-release libappindicator3-1 libgbm1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome

      - save_cache:
          paths:
            - ./vendor/bundle
          key: bundle-cache-{{ checksum "Gemfile.lock" }}

      - run:
          name: Set up database
          command: |
            bundle exec rake db:create db:schema:load

      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
